//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWpfApp
{
  
    
    public partial class Orders
    {
        public int user_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime ordered_at { get; set; }
        public System.DateTime deliver_at { get; set; }
        public string order_status { get; set; }
        public string shipping_address { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
